/**
 * Leonard Controllable Services
 * This is a server for use with Leonard Controllable Services
 *
 * OpenAPI spec version: 1.0.0
 * Contact: matt@leonardgarden.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface EquipmentHistoryLog {
    id?: number;
    timestamp?: string;
    equipmentId?: number;
    value?: string;
}
